group: travis_latest
language: python
sudo: required

python:
  - "2.7.3" # Ubuntu 12.4LTS (precise) and Debian 7 LTS (wheezy)
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"

jobs:
  include:
  - python: "3.7"
    dist: xenial  # https://github.com/travis-ci/travis-ci/issues/9069

install:
  - travis_retry bash test/travis_setup.sh

script:
  - python -m coverage run -m unittest discover
  - python -m coverage combine
  - python -m coverage report 2>&1

after_success:
  coveralls
